const databasePerguntas = [
  { img: "https://lwsinterprise.github.io/CB721.jpg", q: "What messages are given by circular traffic signs that have a blue background?", options: ["They give temporary directions during a diversion", "They give directions to car parks", "They give motorway information", "They give mandatory instructions"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB722.jpg", q: "Where would you see a contraflow bus lane?", options: ["On a dual carriageway", "On a roundabout", "On an urban motorway", "On a one-way street"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB723.jpg", q: "What does this sign mean?", options: ["Bus station on the right", "Contraflow bus lane", "With-flow bus lane", "Give way to buses"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB724.jpg", q: "What does a sign with a brown background show?", options: ["Tourist directions", "Primary roads", "Motorway routes", "Minor roads"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB725.jpg", q: "What does this sign mean?", options: ["Tourist attraction", "Beware of trains", "Level crossing", "Beware of trams"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB726.jpg", q: "What's the purpose of triangular shaped signs?", options: ["To give warnings", "To give information", "To give orders", "To give directions"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB727.jpg", q: "What does this sign mean?", options: ["Turn left ahead", "T-junction", "No through road", "Give way"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB728.jpg", q: "What does this sign mean?", options: ["Multi-exit roundabout", "Risk of ice", "Six roads converge", "Place of historical interest"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB729.jpg", q: "What does this sign mean?", options: ["Crossroads", "Level crossing with gate", "Level crossing without gate", "Ahead only"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB730.jpg", q: "What does this sign mean?", options: ["Ring road", "Mini-roundabout", "No vehicles", "Roundabout"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB731.jpg", q: "What information would be shown in a triangular road sign?", options: ["Road narrows", "Ahead only", "Keep left", "Minimum speed"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB732.jpg", q: "What does this sign mean?", options: ["Cyclists must dismount", "Cycles aren't allowed", "Cycle route ahead", "Cycle in single file"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB733.jpg", q: "Which sign means that pedestrians may be walking along the road?", options: ["", "", "", ""], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB734.jpg", q: "Which sign means there's a double bend ahead?", options: ["", "", "", ""], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB735.jpg", q: "What does this sign mean?", options: ["Wait at the barriers", "Wait at the crossroads", "Give way to trams", "Give way to farm vehicles"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB736.jpg", q: "What does this sign mean?", options: ["Hump bridge", "Humps in the road", "Entrance to tunnel", "Soft verges"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB737.jpg", q: "Which sign means the end of a dual carriageway?", options: ["", "", "", ""], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB738.jpg", q: "What does this sign mean?", options: ["End of dual carriageway", "Tall bridge", "Road narrows", "End of narrow bridge"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB739.jpg", q: "What does this sign mean?", options: ["Side winds", "Road noise", "Airport", "Adverse camber"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB740.jpg", q: "What does this traffic sign mean?", options: ["Slippery road ahead", "Tyres liable to punctures ahead", "Danger ahead", "Service area ahead"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB741.jpg", q: "You're about to overtake. What should you do when you see this sign?", options: ["Overtake the other driver as quickly as possible", "Move to the right to get a better view", "Switch your headlights on before overtaking", "Hold back until you can see clearly ahead"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB742.jpg", q: "What does this sign mean?", options: ["Level crossing with gate or barrier", "Gated road ahead", "Level crossing without gate or barrier", "Cattle grid ahead"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB743.jpg", q: "What does this sign mean?", options: ["No trams ahead", "Oncoming trams", "Trams crossing ahead", "Trams only"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB744.jpg", q: "What does this sign mean?", options: ["Adverse camber", "Steep hill downwards", "Uneven road", "Steep hill upwards"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB745.jpg", q: "What does this sign mean?", options: ["Uneven road surface", "Bridge over the road", "Road ahead ends", "Water across the road"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB746.jpg", q: "What does this sign mean?", options: ["Turn left for parking area", "No through road on the left", "No entry for traffic turning left", "Turn left for ferry terminal"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB747.jpg", q: "What does this sign mean?", options: ["T-junction", "No through road", "Telephone box ahead", "Toilet ahead"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB748.jpg", q: "Which is the sign for a ring road?", options: ["", "", "", ""], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB749.jpg", q: "What does this sign mean?", options: ["The right-hand lane ahead is narrow", "Right-hand lane for buses only", "Right-hand lane for turning right", "The right-hand lane is closed"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB750.jpg", q: "What does this sign mean?", options: ["Change to the left-hand lane", "Leave at the next exit", "Contraflow system", "One-way street"], answer: 2 }
];