const databasePerguntas = [
  { img: "https://lwsinterprise.github.io/CB901.jpg", q: "What's the first thing you must do if you have a collision while you're driving your car?", options: ["Stop only if someone waves at you", "Call the emergency services", "Stop at the scene of the incident", "Call your insurance company"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB902.jpg", q: "What information should you share if you’re involved in a collision that causes damage to another vehicle?", options: ["Your occupation and reason for your journey", "Your name, address and vehicle registration number", "Your national insurance number", "Your internet service provider"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB903.jpg", q: "You lose control of your car and damage a garden wall. What must you do if the property owner isn't available?", options: ["Report the incident to the police within 24 hours", "Go back to tell the house owner the next day", "Report the incident to your insurance company when you get home", "Find someone in the area to tell them about it immediately"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB904.jpg", q: "What restrictions apply if you're towing a trailer on a three-lane motorway?", options: ["You mustn't exceed 50 mph", "You mustn't overtake", "You must have a stabiliser fitted", "You mustn't use the right-hand lane"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB905.jpg", q: "What should you do if you're towing a trailer and it starts to swing from side to side?", options: ["Ease off the accelerator to reduce your speed", "Let go of the steering wheel and let it correct itself", "Brake hard and hold the pedal down", "Accelerate until it stabilises"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB906.jpg", q: "When would you increase the pressure in your tyres so that it's above the normal value?", options: ["When the roads are slippery", "When the vehicle is fitted with anti-lock brakes", "When the tyre tread is worn below 2 mm", "When carrying a heavy load"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB907.jpg", q: "How will a heavy load on your roof rack affect your vehicle's handling?", options: ["It will improve the road holding", "It will reduce the stopping distance", "It will make the steering lighter", "It will reduce stability"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB908.jpg", q: "What would be affected if you carry a very heavy load on your vehicle?", options: ["The vehicle's gearbox", "The vehicle's ventilation", "The vehicle's handling", "The vehicle's battery"], answer: 2 },
  { img: "https://lwsinterprise.github.io/CB909.jpg", q: "Who's responsible for making sure that a vehicle isn't overloaded?", options: ["The driver of the vehicle", "The owner of the items being carried", "The person who loaded the vehicle", "The licensing authority"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB910.jpg", q: "You're planning to tow a caravan. What will help the handling of the combination?", options: ["A jockey wheel fitted to the tow bar", "Power steering fitted to the towing vehicle", "Anti-lock brakes fitted to the towing vehicle", "A stabiliser fitted to the tow bar"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB911.jpg", q: "Are passengers allowed to ride in a caravan that's being towed?", options: ["Yes, if they're over 14", "No, not at any time", "Only if all the seats in the towing vehicle are full", "Only if a stabiliser is fitted"], answer: 1 },
  { img: "https://lwsinterprise.github.io/CB912.jpg", q: "What safety device must be fitted to a trailer braking system?", options: ["Stabiliser", "Jockey wheel", "Corner steadies", "Breakaway cable"], answer: 3 },
  { img: "https://lwsinterprise.github.io/CB913.jpg", q: "You wish to tow a trailer. Where would you find the maximum noseweight for your vehicle’s tow hitch?", options: ["In the vehicle handbook", "In The Highway Code", "In your vehicle registration certificate", "In your licence documents"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB914.jpg", q: "How should a load be carried on your roof rack?", options: ["Securely fastened with suitable restraints", "Loaded towards the rear of the vehicle", "Visible in your exterior mirror", "Covered with plastic sheeting"], answer: 0 },
  { img: "https://lwsinterprise.github.io/CB915.jpg", q: "You're carrying a child under three years old in your car. Which restraint is suitable for a child of this age?", options: ["A child seat", "An adult holding a child", "An adult seat belt", "An adult lap belt"], answer: 0 }
];